version: '2.2'

services:
  api:
    image: flippercoin/flaskapp:5
    expose:
      - "5000"
    depends_on: 
      - redis
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on: 
      - api
  redis:
    image: redis:alpine
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  producer:
    image: flippercoin/producer:4
    depends_on: 
      rabbitmq:
        condition: service_healthy