version: '3'

services:
  api:
    image: flippercoin/flaskapp:5
    expose:
      - "5000"
    depends_on: 
      - redis
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on: 
      - api
  redis:
    image: redis:alpine